apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment-dev
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dev
  template:
    metadata:
      labels:
        app: nginx-dev
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
